import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import "./globals.css";
import SidebarLayout from "@/components/SidebarLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <SidebarLayout>
          {children}
          {auth}
        </SidebarLayout>
      </body>
    </html>
  );
}
